main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('players/', views.players_index, name='players_index'),
    path('player/<int:player_id>/', views.player_detail, name='player_detail'),
    #crud path
    path('players/create/', views.PlayerCreate.as_view(), name='player_create'),
    path('players/<int:pk>/update/', views.PlayerUpdate.as_view(), name='player_update'),
    path('players/<int:pk>/delete/', views.PlayerDelete.as_view(), name='player_delete'),
    #alt model route
    path('players/<int:player_id>/add_win/', views.add_win, name='add_win'),
    # character routes
    path('characters/', views.CharacterIndex.as_view(), name='character_index'),
    path('characters/create/', views.CharacterCreate.as_view(), name='character_create'),
    path('characters/<int:pk>/', views.CharacterDetail.as_view(), name='character_detail'),
    path('characters/<int:pk>/update/', views.CharacterUpdate.as_view(), name='character_update'),
    path('characters/<int:pk>/delete/', views.CharacterDelete.as_view(), name='character_delete'),
    # M:M
    path('players/<int:player_id>/assoc_character/<int:character_id>/', views.assoc_character, name='assoc_character'),        
    path('players/<int:player_id>/unassoc_character/<int:character_id>/', views.unassoc_character, name='unassoc_character'),
    path('accounts/signup/', views.signup, name='signup'),
]

playercollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.

class Character(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.color}{self.name}"
    
    def get_absolute_url(self):
        return reverse('character_detail', kwargs={'pk': self.id})

class Player(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField(default=0)
    current_rank = models.IntegerField(default=1)
    alltime_rank = models.IntegerField(default=1)
    
    characters = models.ManyToManyField(Character)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('player_detail', kwargs={'player_id': self.id})
    
class Win(models.Model):
    tourney_wins = models.CharField(max_length=100)
    date = models.DateField()

    player = models.ForeignKey(Player, on_delete=models.CASCADE)

    def __str__(self):
        return f'This player won {self.tourney_wins}'
    
    class Meta: 
        ordering = ['-date']
    
   

main_app/forms.py
from django.forms import ModelForm
from .models import Win

class TourneyForm(ModelForm):
    class Meta:
        model = Win
        fields = ['tourney_wins', 'date']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView

from .models import Player, Character
from .forms import TourneyForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def players_index(request):
    players = Player.objects.filter(user=request.user)
    return render(request, 'players/index.html', {'players': players})

@login_required
def player_detail(request, player_id):
    player = Player.objects.get(id=player_id)
    win_form = TourneyForm()
    player_character_ids = player.characters.all().values_list('id')
    characters_player_doesnt_play = Character.objects.exclude(id__in=player_character_ids)
    return render(request, 'players/detail.html', {
        'player': player, 
        'win_form': win_form,
        'characters': characters_player_doesnt_play
    })

@login_required
def add_win(request, player_id):
    form = TourneyForm(request.POST)
    if form.is_valid():
        new_win = form.save(commit=False)
        new_win.player_id = player_id
        new_win.save()
    return redirect('player_detail', player_id=player_id)

@login_required
def assoc_character(request, player_id, character_id):
    player = Player.objects.get(id=player_id)
    player.characters.add(character_id)
    return redirect('player_detail', player_id=player_id)

@login_required
def unassoc_character(request, player_id, character_id):
    player = Player.objects.get(id=player_id)
    player.characters.remove(character_id)
    return redirect('player_detail', player_id=player_id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user =form.save()
            login(request, user)
            return redirect('players_index')
        else:
            error_message = 'Invalid Sign In'
    form = UserCreationForm()
    return render(request, 'registration/signup.html', {
        'form': form,
        'error': error_message
    })
    

class PlayerCreate(LoginRequiredMixin, CreateView):
    model = Player
    fields = 'name', 'age', 'current_rank', 'alltime_rank'
    template_name = 'players/player_form.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class PlayerUpdate(LoginRequiredMixin, UpdateView):
    model = Player
    fields = ('age', 'current_rank', 'alltime_rank')
    template_name = 'players/player_form.html'

class PlayerDelete(LoginRequiredMixin, DeleteView):
    model = Player
    template_name = 'players/player_confirm_delete.html'
    success_url = '/players/'

class CharacterIndex(LoginRequiredMixin, ListView):
    model = Character
    
class CharacterUpdate(LoginRequiredMixin, UpdateView):
    model = Character
    fields = '__all__'
    
class CharacterDelete(LoginRequiredMixin, DeleteView):
    model = Character
    success_url = '/characters/'
    
class CharacterDetail(LoginRequiredMixin, DetailView):
    model = Character
    
class CharacterCreate(LoginRequiredMixin, CreateView):
    model = Character
    fields = '__all__'

main_app/templates/about.html
{% extends 'base.html' %}

{% block title %}
<title>About Player Collector</title>
{% endblock %}

{% block content %}

<h1 class="text-center p-2">About the Players</h1>

<div class="container">
    <h3>
        Players from around the world compete 1 on 1, or on a team against others for a chance at the number
        one spot in their specific game. They continue to challenge themselves, while pushing others to their limit.
        
    </h3>
</div>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    {% block title %}
    <title>Player Collector</title>
    {% endblock %}
</head>
<body>
    <header class="container-fluid">
        <nav class="navbar bg-dark container-fluid navbar-expand-lg">
            <a class="navbar-brand text-light m-2" href="/">PlayerCollector</a>
            <button class="navbar-toggler m-2 navbar-dark" 
                type="button" 
                data-bs-toggle="collapse" 
                data-bs-target="#navbarContent" 
                aria-controls="#navbarContent" 
                aria-expanded="false" 
                aria-label="Toggle Navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarContent">
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link active link-info" aria-current="page" href="{% url 'about' %}">About</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <a class='nav-link active link-info' aria-current="page" href="{% url 'players_index' %}">View Players</a>
                    </li>
                    <li>
                        <a class="nav-link active link-info" aria-current="page" href="{% url 'player_create' %}">Add A Player</a>
                    </li>
                    <li>
                        <a class="nav-link active link-info" aria-current="page" href="{% url 'character_create' %}">Add A Character</a>
                    </li>
                    <li>
                        <a class="nav-link active link-info" aria-current="page" href="{% url 'character_index' %}">View Character Choices</a>
                    </li>
                    <li>
                        <a class="nav-link active link-info" aria-current="page" href="{% url 'logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li>
                        <a class="nav-link active link-info" aria-current="page" href="{% url 'login' %}">Login</a>
                    </li>
                    <li>
                        <a class="nav-link active link-info" aria-current="page" href="{% url 'signup' %}">Signup</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer class="footer container-fluid text-light bg-dark">
        <p>Copyright &copy; All Rights Reserved Player Collector 2023</p>
    </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}

{% block title %}
<title>Player Collector Home</title>
{% endblock %}

{% block content %}

<h1 class="text-center p-2">Home page</h1>    
<div class="container">
<h3>The player collector allows a user to hold all of their favorite players and their stats. They can add info for any videogame, as well as the character used in the game. Tournament wins can be added to each player in the list.</h3>
</div>
{% endblock %}

main_app/templates/main_app/character_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1 class="p-2 text-center">Delete Character</h1>

<h4 class="p-2 text-center">Are you sure you want to delete <span> {{object.color}} {{object.name}} </span></h4>

<div class="row justify-content-center">
    <div class="col-auto">
        <form method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-info" value="Delete">
            <a class="btn btn-info" href="{% url 'character_detail' object.id %}">Cancel</a>
        </form>
    </div>
</div>
{% endblock %}

main_app/templates/main_app/character_detail.html
{% extends 'base.html' %}

{% block title %}
<title>Character Details</title>
{% endblock %}

{% block content %}
<h1 class="p-2 text-center">Character Details</h1>

<div class="row justify-content-center">
    <div class="col-auto">
        <span> <h3>{{object.color.capitalize}} {{object.name.capitalize}}</h3></span>
        <a class="btn btn-info" href="{% url 'character_update' object.id %}">Edit</a>
        <a class="btn btn-info" href="{% url 'character_delete' object.id %}">Delete</a>
    </div>
</div>

{% endblock %}

main_app/templates/main_app/character_form.html
{% extends 'base.html' %}

{% block title %}
{% if object %}
<title>Edit Character</title>
{% else %}
<title>Add New Character</title>
{% endif %}
{% endblock %}

{% block content %}
{% if object %}

<h1 class="text-center">Edit <span> {{object.color.capitalize}} {{object.name.capitalize}} </span></h1>

{% else %}

<h1 class="text-center p-2">Add New Character</h1>

{% endif %}

<div class="row justify-content-center">
    <div class="col-auto">
        <form method="POST">
            {% csrf_token %}
            <table class="table">
                {{ form.as_table }}
            </table>
            <input type="submit" value="Submit" class="btn btn-info">
        </form>
    </div>
</div>

{% endblock %}

main_app/templates/main_app/character_list.html
{% extends 'base.html' %}

{% block title %}
<title>Character List</title>
{% endblock %}

{% block content %}
<h1 class="text-center p-2">Character List</h1>

<div class="container">
    <div class="row g-5">
        {% for character in object_list %}
        <div class="col-md-3 col-6 text-center">
            <a class="btn btn-info" href="{% url 'character_detail' character.id %}">
                <span> {{ character.color.capitalize }} {{ character.name.capitalize }} </span>
            </a>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

main_app/templates/players/detail.html
{% extends 'base.html' %}

{% block title %}
<title>Player Details</title>
{% endblock %}

{% block content %}

<h1 class="text-center p-2">Player Details</h1>

<div class="container">
    <div class="row p-2 justify-content-center">
        <div class="col-6 p-2">
            <h2>Name: {{ player.name}}</h2>
            <h5>Age: {{ player.age }}</h5>
            <h5>Current Rank: {{ player.current_rank }}</h5>
            <h5>Alltime Rank: {{ player.alltime_rank }}</h5>
        </div>
        <div class="col-6 p-2 text-center">
            <form action="{% url 'add_win' player.id %}" method="POST">
                {% csrf_token %}
                {{ win_form.as_p }}
                <input class="btn btn-info" type="submit" value="Add Win">
            </form>
        </div>
    </div>
    <div class="row p-2 justify-content-center">
        <div class="col-md-6 col-6 p-2">
            <table class="table mx-auto">
                <thead>
                    <tr>
                        <th class="p-2 text-center">Date</th>
                        <th class="p-2 text-center">Tourney Wins</th>
                    </tr>
                </thead>
                <tbody>
                    {% for win in player.win_set.all %}
                        <tr>
                            <td class="p-2 text-center">{{ win.date }}</td>
                            <td class="p-2 text-center">{{ win.tourney_wins}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-md-6 col-6 p-3 text-center">
            <a class="btn btn-info m-1" href="{% url 'player_update' player.id %}">Update Player</a>
            <a class="btn btn-info m-1" href="{% url 'player_delete' player.id %}">Delete Player</a>
        </div>
    </div>
    <div class="row p-2 justify-content-center">
        <div class="col-6">
            <div class="row">
                {% if player.characters.count %}
                <h3 class="p-2 text-center">Characters In Use</h3>
                {% for character in player.characters.all %}
                <div class="col">
                    <div class="text-center">
                        <span> {{character.color}} {{character.name}} </span>
                        <div>
                            <form action="{% url 'unassoc_character' player.id character.id %}" method="POST">
                                {% csrf_token %}
                                <input type="submit" value="Remove" class="btn btn-danger">
                            </form>
                        </div>
                   </div>
                </div>
                {% endfor %}
                {% else %}
                <h5 class="p-2 text-center">No Characters Played</h5>
                {% endif %}
            </div>
        </div>
        <div class="col-6">
            <div class="row">
                {% if characters.count %}
                <h3 class="p-2 text-center">Character Choices</h3>
                {% for character in characters %}
                <div class="col">
                    <div class="text-center">
                        <span> {{ character.color.capitalize }} {{ character.name.capitalize }} </span>
                        <form action="{% url 'assoc_character' player.id character.id %}" method="POST">
                            {% csrf_token %}
                            <input type="submit" value="Add" class="btn btn-info">
                        </form>
                    </div>
                </div>
                {% endfor %}
                {% else %}
                <h1 class="p-2 text-center">No Characters</h1>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<script>
    const datePickerEl = document.getElementById('id_date')
    const formSelectEl = document.getElementById('id_tourney_wins')

    M.Datepicker.init(datePickerEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    })
    M.updateTextFields.init(formSelectEl)
</script>



{% endblock %}

main_app/templates/players/index.html
{% extends 'base.html' %}

{% block title%}
<title>Players</title>
{% endblock %}

{% block content%}

<h1 class="text-center p-2">Players</h1>


<div class="container">
    <div class="row g-5">
        {% for player in players %}
        <div class="col-md-3 col-6 text-center">
            <a class="btn btn-info" href="{% url 'player_detail' player.id %}">
                 <span>{{ player.name }}</span>
            </a>
        </div>
        {% endfor %}
    </div>
</div>




{% endblock %}

main_app/templates/players/player_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
<title>Delete {{ object.name }}</title>
{% endblock %}

{% block content %}
<h1 class="text-center p-2">Are You Sure You Want To Delete {{ object.name }}?</h1>

<form method="POST">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-2">
                {% csrf_token %}
                <input class="btn btn-info" type="submit" value="Yes">
                <a class="btn btn-info" href="{% url 'player_detail' object.id %}">No</a>
            </div>
        </div>  
    </div>  
</form>

{% endblock %}

main_app/templates/players/player_form.html
{% extends 'base.html' %}

{% block title %}
{% if object %}
<title>Update {{ object.name}}'s Stats</title>
{% else %}
<title>Add a New Player</title>
{% endif %}
{% endblock %}

{% block content %}
{% if object %}
<h1 class="text-center p-2">Update Player</h1>
{% else %}
<h1 class="text-center p-2">Add a New Player</h1>
{% endif %}

<div class="row">
    <div class="mx-auto col-10 col-md-8 col-lg-6">
        <form method="POST">
            <div class="row justify-content-center">
                <div class="col-auto">
                    {% csrf_token %}
                    <table class="table">
                    {{ form.as_table }}
                    </table>
                    <input class="btn btn-info justify-content-center" type="submit" value="Submit">
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}